### ISSUE TITLE
Windows Defender is reporting this module as trojan

### ISSUE THREAD

**Issue by SoftwareRat** [googleprojectzero/sandbox-attacksurface-analysis-tools#54]
Windows Defender is reporting the module as `Trojan:Win32/Tiggre!rfn`:`NtApiDotNet.Forms.dll` and `Trojan:Win32/Wacatac.B!ml`:`ViewSecurityDescriptor.exe`

**Comment by tyranid** [comment]
Unfortunately this is a known problem, Windows Defender is garbage. I've had this exact detection many times, each time I report the binary to MS and they remove the detection for that specific file, only for it to come back again at some later date usually because of a recompile. You have two choices, either disable the garbage "Cloud" detections which this is (it's a machine learning signature with no bearing on reality) or submit the binary to MS citing it as a false positive and see if they'll fix it. I really can't do anything more.
